export default {
  login: "tanaypratap",
  id: 10216863,
  node_id: "MDQ6VXNlcjEwMjE2ODYz",
  avatar_url: "https://avatars.githubusercontent.com/u/10216863?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/tanaypratap",
  html_url: "https://github.com/tanaypratap",
  followers_url: "https://api.github.com/users/tanaypratap/followers",
  following_url: "https://api.github.com/users/tanaypratap/following{/other_user}",
  gists_url: "https://api.github.com/users/tanaypratap/gists{/gist_id}",
  starred_url: "https://api.github.com/users/tanaypratap/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/tanaypratap/subscriptions",
  organizations_url: "https://api.github.com/users/tanaypratap/orgs",
  repos_url: "https://api.github.com/users/tanaypratap/repos",
  events_url: "https://api.github.com/users/tanaypratap/events{/privacy}",
  received_events_url: "https://api.github.com/users/tanaypratap/received_events",
  type: "User",
  site_admin: false,
  name: "Tanay Pratap",
  company: "Microsoft",
  blog: "tanaypratap.com",
  location: "Bangalore, India",
  email: null,
  hireable: null,
  bio: "Engineering Web @microsoft, teaching at learncodingfree.org",
  twitter_username: "tanaypratap",
  public_repos: 37,
  public_gists: 20,
  followers: 1932,
  following: 0,
  created_at: "2014-12-17T05:15:06Z",
  updated_at: "2021-08-23T14:30:37Z"
  }
